//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int key { get; set; }
        public string BookID { get; set; }
        public string TransactionID { get; set; }
        public Nullable<System.DateTime> DateActualReturn { get; set; }
        public string BorrowStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual IssueTran IssueTran { get; set; }
    }
}
